import type { PharmacyProduct } from './types';

/**
 * Klinika dorixona katalogi — maqsad/tur bo‘yicha kategoriyalangan.
 * ID lar barqaror (seed qayta qo‘shilganda dublikat bo‘lmasin).
 */
export const INITIAL_PHARMACY_PRODUCTS: PharmacyProduct[] = [
  // —— Antibiotiklar ——
  {
    id: 'pharm-abx-cefotaxime',
    barcode: '',
    rowNum: 1,
    name: 'Цефотаксим-БХФЗ (Cefotaxime)',
    unit: '1 g',
    group: 'Antibiotiklar',
    type: 'Flakon (kukun)',
    packageCount: 1,
    status: 'Актив',
    category: 'antibiotics',
  },

  // —— Aminokislotalar ——
  {
    id: 'pharm-aa-elcin',
    barcode: '',
    rowNum: 2,
    name: 'Элцин (L-arginin gidroxlorid)',
    unit: '100 ml (42 mg/ml)',
    group: 'Aminokislotalar',
    type: 'Flakon (eritma)',
    packageCount: 1,
    status: 'Актив',
    category: 'amino_acids',
  },

  // —— Anesteziklar ——
  {
    id: 'pharm-anes-novocaine',
    barcode: '',
    rowNum: 3,
    name: 'Novokain - LIK (0.5%)',
    unit: '5 ml (5 dona ampula)',
    group: 'Anesteziklar',
    type: 'Quti / Ampula',
    packageCount: 5,
    status: 'Актив',
    category: 'anesthetics',
  },

  // —— Infuziya eritmalari ——
  {
    id: 'pharm-inf-ksilat',
    barcode: '',
    rowNum: 4,
    name: 'Ksilat (Ksilat / Ксилат)',
    unit: 'Shisha flakon',
    group: 'Infuziya eritmalari',
    type: 'Flakon (infuziya)',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-nacl-100-radiks',
    barcode: '',
    rowNum: 5,
    name: 'Izotonik (Natriy xlorid 0.9% - Radiks)',
    unit: '100 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-nacl-200',
    barcode: '',
    rowNum: 6,
    name: 'Izotonik (Natriy xlorid 0.9%)',
    unit: '200 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-nacl-500',
    barcode: '',
    rowNum: 7,
    name: 'Natriy Xlorid (0.9%)',
    unit: '500 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-ringer-500',
    barcode: '',
    rowNum: 8,
    name: 'Ringer (Рингер)',
    unit: '500 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-ringer-lactate-200',
    barcode: '',
    rowNum: 9,
    name: 'Ringer Laktat (Рингер Лактат)',
    unit: '200 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-disol-200',
    barcode: '',
    rowNum: 10,
    name: 'MR Disol (Disol)',
    unit: '200 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-nahco3-200',
    barcode: '',
    rowNum: 11,
    name: 'Natriy Gidrokarbonat (4%)',
    unit: '200 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-glukoza-merrymed-250',
    barcode: '',
    rowNum: 12,
    name: 'MR Glukoza (Merrymed Farm)',
    unit: '250 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-glukoza-jurabek-500',
    barcode: '',
    rowNum: 13,
    name: 'Glyukoza - Jurabek (5%)',
    unit: '500 ml',
    group: 'Infuziya eritmalari',
    type: 'Plastik flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-reosorbilakt',
    barcode: '',
    rowNum: 14,
    name: 'Reosorbilakt (Yuria-Pharm)',
    unit: 'Shisha flakon',
    group: 'Infuziya eritmalari',
    type: 'Shisha flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },
  {
    id: 'pharm-inf-soda-bufer',
    barcode: '',
    rowNum: 15,
    name: 'Soda-Bufer (Yuria-Pharm - 42 mg/ml)',
    unit: 'Shisha flakon',
    group: 'Infuziya eritmalari',
    type: 'Shisha flakon',
    packageCount: 1,
    status: 'Актив',
    category: 'infusions',
  },

  // —— Diabet vositalari ——
  {
    id: 'pharm-dm-aria-strips',
    barcode: '',
    rowNum: 16,
    name: 'Aria GLC Test tasmalari (Glyukoza)',
    unit: '50 dona',
    group: 'Diabet vositalari',
    type: 'Quti (test-poloska)',
    packageCount: 50,
    status: 'Актив',
    category: 'diabetes',
  },
  {
    id: 'pharm-dm-aria-meter',
    barcode: '',
    rowNum: 17,
    name: 'Aria GLC Glyukometr to‘plami',
    unit: '1 dona (komplekt)',
    group: 'Diabet vositalari',
    type: 'Apparat + ruchka + 10 ta strip',
    packageCount: 1,
    status: 'Актив',
    category: 'diabetes',
  },

  // —— Sarf materiallari ——
  {
    id: 'pharm-cons-beroblade',
    barcode: '',
    rowNum: 18,
    name: 'Beroblade (Beromed)',
    unit: 'Quti',
    group: 'Sarf materiallari',
    type: 'Jarrohlik skalpeli',
    packageCount: 1,
    status: 'Актив',
    category: 'consumables',
  },
  {
    id: 'pharm-cons-cotton-club',
    barcode: '',
    rowNum: 19,
    name: 'Cotton Club Paxta (Bata)',
    unit: '1 dona (o‘ram)',
    group: 'Sarf materiallari',
    type: 'Tibbiy paxta',
    packageCount: 1,
    status: 'Актив',
    category: 'consumables',
  },
  {
    id: 'pharm-cons-sistema-tbl150',
    barcode: '',
    rowNum: 20,
    name: 'Sistema (Infuzion sistema TBL-150)',
    unit: '1 dona',
    group: 'Sarf materiallari',
    type: 'Bir martalik tomchilatgich',
    packageCount: 1,
    status: 'Актив',
    category: 'consumables',
  },
  {
    id: 'pharm-cons-shpris-23g',
    barcode: '',
    rowNum: 21,
    name: 'Shpris Health Line (23G)',
    unit: '2 ml / cc (1 dona)',
    group: 'Sarf materiallari',
    type: 'Ignali shpris',
    packageCount: 1,
    status: 'Актив',
    category: 'consumables',
  },
];
