import type { PharmacyCategoryId, PharmacyProduct } from "./types";

/** [t/r, nomi, o'lchov, guruh, turi, upakovka, kategoriya] */
type Row = [
  number,
  string,
  string,
  string,
  string,
  number,
  PharmacyCategoryId,
];

const ROWS: Row[] = [
  [1, "Metformin 500 mg", "tab.", "Qandli diabet", "Таблетка", 60, "diabetes"],
  [2, "Metformin 850 mg", "tab.", "Qandli diabet", "Таблетка", 60, "diabetes"],
  [3, "Metformin 1000 mg", "tab.", "Qandli diabet", "Таблетка", 60, "diabetes"],
  [4, "Gliklazid 30 mg MR", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [5, "Gliklazid 60 mg MR", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [6, "Glimepirid 1 mg", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [7, "Glimepirid 2 mg", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [8, "Sitagliptin 100 mg", "tab.", "Qandli diabet", "Таблетка", 28, "diabetes"],
  [9, "Vildagliptin 50 mg", "tab.", "Qandli diabet", "Таблетка", 28, "diabetes"],
  [10, "Empagliflozin 10 mg", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [11, "Empagliflozin 25 mg", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [12, "Dapagliflozin 10 mg", "tab.", "Qandli diabet", "Таблетка", 30, "diabetes"],
  [13, "Insulin glargin", "ruchka/fl.", "Qandli diabet", "Инъекция", 5, "diabetes"],
  [14, "Insulin detemir", "ruchka/fl.", "Qandli diabet", "Инъекция", 5, "diabetes"],
  [15, "Insulin aspart", "ruchka/fl.", "Qandli diabet", "Инъекция", 5, "diabetes"],
  [16, "Insulin lispro", "ruchka/fl.", "Qandli diabet", "Инъекция", 5, "diabetes"],
  [17, "Regular insulin", "fl.", "Qandli diabet", "Инъекция", 1, "diabetes"],
  [18, "NPH insulin", "fl.", "Qandli diabet", "Инъекция", 1, "diabetes"],
  [19, "Glukagon emergency kit", "набор", "Shoshilinch yordam", "Инъекция", 1, "emergency"],
  [20, "Glyukoza 40% 20 ml", "amp.", "Shoshilinch yordam", "Инъекция", 10, "emergency"],
  [21, "Amlodipin 5 mg", "tab.", "Qon bosimi", "Таблетка", 30, "blood_pressure"],
  [22, "Amlodipin 10 mg", "tab.", "Qon bosimi", "Таблетка", 30, "blood_pressure"],
  [23, "Enalapril 5 mg", "tab.", "Qon bosimi", "Таблетка", 20, "blood_pressure"],
  [24, "Enalapril 10 mg", "tab.", "Qon bosimi", "Таблетка", 20, "blood_pressure"],
  [25, "Kaptopril 25 mg", "tab.", "Qon bosimi", "Таблетка", 40, "blood_pressure"],
  [26, "Losartan 50 mg", "tab.", "Qon bosimi", "Таблетка", 30, "blood_pressure"],
  [27, "Losartan 100 mg", "tab.", "Qon bosimi", "Таблетка", 30, "blood_pressure"],
  [28, "Valsartan 80 mg", "tab.", "Qon bosimi", "Таблетка", 28, "blood_pressure"],
  [29, "Telmisartan 40 mg", "tab.", "Qon bosimi", "Таблетка", 30, "blood_pressure"],
  [30, "Bisoprolol 2.5 mg", "tab.", "Yurak-qon tomir", "Таблетка", 30, "blood_pressure"],
  [31, "Bisoprolol 5 mg", "tab.", "Yurak-qon tomir", "Таблетка", 30, "blood_pressure"],
  [32, "Nebivolol 5 mg", "tab.", "Yurak-qon tomir", "Таблетка", 28, "blood_pressure"],
  [33, "Indapamid 1.5 mg", "tab.", "Qon bosimi/diuretik", "Таблетка", 30, "blood_pressure"],
  [34, "Gidroxlorotiazid 25 mg", "tab.", "Qon bosimi/diuretik", "Таблетка", 20, "blood_pressure"],
  [35, "Spironolakton 25 mg", "tab.", "Diuretik", "Таблетка", 30, "blood_pressure"],
  [36, "Furosemid 40 mg", "tab.", "Diuretik", "Таблетка", 50, "blood_pressure"],
  [37, "Furosemid 20 mg/2 ml", "amp.", "Diuretik", "Инъекция", 10, "blood_pressure"],
  [38, "Aspirin cardio 75 mg", "tab.", "Antiagregant", "Таблетка", 30, "blood_pressure"],
  [39, "Clopidogrel 75 mg", "tab.", "Antiagregant", "Таблетка", 28, "blood_pressure"],
  [40, "Atorvastatin 20 mg", "tab.", "Dislipidemiya", "Таблетка", 30, "blood_pressure"],
  [41, "Rosuvastatin 10 mg", "tab.", "Dislipidemiya", "Таблетка", 30, "blood_pressure"],
  [42, "Paratsetamol 500 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 10, "pain"],
  [43, "Ibuprofen 200 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 20, "pain"],
  [44, "Ibuprofen 400 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 20, "pain"],
  [45, "Diklofenak 50 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 20, "pain"],
  [46, "Diklofenak 75 mg/3 ml", "amp.", "Og'riq qoldiruvchi", "Инъекция", 5, "pain"],
  [47, "Ketorolak 10 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 20, "pain"],
  [48, "Ketorolak 30 mg/ml", "amp.", "Og'riq qoldiruvchi", "Инъекция", 10, "pain"],
  [49, "Meloksikam 7.5 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 20, "pain"],
  [50, "Meloksikam 15 mg", "tab.", "Og'riq qoldiruvchi", "Таблетка", 10, "pain"],
  [51, "Drotaverin 40 mg", "tab.", "Spazmolitik", "Таблетка", 20, "pain"],
  [52, "Drotaverin 2 ml", "amp.", "Spazmolitik", "Инъекция", 10, "pain"],
  [53, "Omeprazol 20 mg", "kaps.", "Oshqozon himoyasi", "Капсула", 30, "blood_pressure"],
  [54, "Pantoprazol 40 mg", "tab.", "Oshqozon himoyasi", "Таблетка", 28, "blood_pressure"],
  [55, "Pantoprazol 40 mg", "fl.", "Oshqozon himoyasi", "Инъекция", 1, "blood_pressure"],
  [56, "Magniy sulfat 25% 10 ml", "amp.", "Shoshilinch yordam", "Инъекция", 10, "emergency"],
  [57, "Kaliy xlorid 4% 10 ml", "amp.", "Elektrolitlar", "Инъекция", 10, "infusions"],
  [58, "Kalsiy glyukonat 10% 10 ml", "amp.", "Elektrolitlar", "Инъекция", 10, "infusions"],
  [59, "Natriy xlorid 0.9% 100 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [60, "Natriy xlorid 0.9% 200 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [61, "Natriy xlorid 0.9% 400/500 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [62, "Glyukoza 5% 200 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [63, "Glyukoza 5% 400/500 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [64, "Ringer laktat 500 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [65, "Natriy gidrokarbonat 4% 200 ml", "fl.", "Infuziyalar", "Инфузия", 1, "infusions"],
  [66, "Tiamin (vitamin B1)", "amp.", "Vitaminlar", "Инъекция", 10, "infusions"],
  [67, "Piridoksin (vitamin B6)", "amp.", "Vitaminlar", "Инъекция", 10, "infusions"],
  [68, "Sianokobalamin (vitamin B12)", "amp.", "Vitaminlar", "Инъекция", 10, "infusions"],
  [69, "Alfa-lipoik kislota 600 mg", "tab.", "Diabetik neyropatiya", "Таблетка", 30, "diabetes"],
  [70, "Alfa-lipoik kislota infuziya", "fl./amp.", "Diabetik neyropatiya", "Инъекция", 5, "diabetes"],
  [71, "Pregabalin 75 mg", "kaps.", "Neyropatik og'riq", "Капсула", 28, "pain"],
  [72, "Gabapentin 300 mg", "kaps.", "Neyropatik og'riq", "Капсула", 30, "pain"],
  [73, "Levotiroksin 25 mkg", "tab.", "Qalqonsimon bez", "Таблетка", 50, "thyroid"],
  [74, "Levotiroksin 50 mkg", "tab.", "Qalqonsimon bez", "Таблетка", 50, "thyroid"],
  [75, "Levotiroksin 100 mkg", "tab.", "Qalqonsimon bez", "Таблетка", 50, "thyroid"],
  [76, "Tiamazol 5 mg", "tab.", "Qalqonsimon bez", "Таблетка", 50, "thyroid"],
  [77, "Deksametazon 4 mg/ml", "amp.", "Gormonal/tez yordam", "Инъекция", 25, "emergency"],
  [78, "Gidrokortizon 100 mg", "fl.", "Gormonal/tez yordam", "Инъекция", 1, "emergency"],
  [79, "Loratadin 10 mg", "tab.", "Antigistamin", "Таблетка", 10, "emergency"],
  [80, "Xloropiramin (Suprastin)", "amp./tab.", "Antigistamin", "Инъекция/Таблетка", 10, "emergency"],
  [81, "Spirt 70%", "ml/fl.", "Antiseptik", "Расходный материал", 1, "consumables"],
  [82, "Xlorheksidin", "fl.", "Antiseptik", "Расходный материал", 1, "consumables"],
  [83, "Paxta", "gr", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [84, "Bint steril", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [85, "Steril salfetka", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 10, "consumables"],
  [86, "Tibbiy niqob", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 50, "consumables"],
  [87, "Steril qo‘lqop", "juft", "Bir martalik tibbiy vositalar", "Расходный материал", 50, "consumables"],
  [88, "1 ml shprits", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [89, "2 ml shprits", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [90, "5 ml shprits", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [91, "10 ml shprits", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [92, "Insulin shprits", "dona", "Qandli diabet uchun vosita", "Расходный материал", 1, "consumables"],
  [93, "Insulin ruchka ignasi", "dona", "Qandli diabet uchun vosita", "Расходный материал", 100, "consumables"],
  [94, "Sistema", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [95, "Angiokatetr", "dona", "Bir martalik tibbiy vositalar", "Расходный материал", 1, "consumables"],
  [96, "Glukometr test stripi", "quti", "Diagnostika", "Расходный материал", 50, "consumables"],
  [97, "Lanset", "dona", "Diagnostika", "Расходный материал", 100, "consumables"],
  [98, "Glukometr", "dona", "Tibbiy jihoz", "Доп.процедуры", 1, "consumables"],
  [99, "Tonometr", "dona", "Tibbiy jihoz", "Доп.процедуры", 1, "consumables"],
  [100, "Termometr", "dona", "Tibbiy jihoz", "Доп.процедуры", 1, "consumables"],
];

export function buildInitialPharmacyProducts(): PharmacyProduct[] {
  return ROWS.map(([rowNum, name, unit, group, type, packageCount, category]) => ({
    id: `pharm-${rowNum}`,
    barcode: "",
    rowNum,
    name,
    unit,
    group,
    type,
    packageCount,
    status: "Актив",
    category,
  }));
}

export const INITIAL_PHARMACY_PRODUCTS = buildInitialPharmacyProducts();
