import type { MedicalService } from "./types";

function row(
  id: string,
  code: string,
  name: string,
  medicalServiceGroup: string,
  medicalServicesGroup: string,
  status = "Актив",
  roomNumber = "",
  doctorLevel = "",
): MedicalService {
  return {
    id,
    code,
    name,
    roomNumber,
    doctorLevel,
    medicalServiceGroup,
    medicalServicesGroup,
    status,
  };
}

export const INITIAL_MEDICAL_SERVICES: MedicalService[] = [
  row("65552", "0001", "Tomirdan qon olish", "Laboratoriya", "Медицинские услуги"),
  row("65063", "0002", "Umumiy qon tahlili", "Laboratoriya", "Медицинские услуги"),
  row("65066", "0003", "Umumiy Siydik Tahlili", "Laboratoriya", "Медицинские услуги"),
  row("65207", "0004", "Nechiporenko sinamasi", "Laboratoriya", "Медицинские услуги"),
  row("65595", "0005", "Biokimyoviy qon tahlili", "Laboratoriya", "Медицинские услуги"),
  row("65585", "0006", "MIKROELEMENTLAR", "Laboratoriya", "Медицинские услуги"),
  row("65557", "0007", "Leykoformula", "Laboratoriya", "Медицинские услуги"),
  row("65556", "0008", "Lipidlar spektri", "Laboratoriya", "Медицинские услуги"),
  row("65210", "0008", "Koulogramma", "Laboratoriya", "Медицинские услуги"),
  row(
    "65203",
    "0009",
    "Qon guruhi va rezus faktorni aniqlash",
    "Laboratoriya",
    "Медицинские услуги",
  ),
  row("65057", "001", "Endokrinolog ko'rigi", "Shifokor ko'rigi", "Консультация"),
  row("65397", "001", "Qon olish", "Lab", "Медицинские услуги"),
  row("65065", "0010", "Qalqonsimon bez gormonlari", "Laboratoriya", "Медицинские услуги"),
  row("65560", "0011", "VITAMINLAR VA ANEMIYA IXLA (CLIA)", "Laboratoriya", "Медицинские услуги"),
  row("65561", "0012", "GORMONLAR IXLA (CLIA)", "Laboratoriya", "Медицинские услуги"),
  row("65566", "0013", "Kateloxaminlar", "Laboratoriya", "Медицинские услуги"),
  row("65067", "0013", "Glukozaga tolerantlik test tahlili", "Laboratoriya", "Медицинские услуги"),
  row("65204", "0014", "VSK", "Laboratoriya", "Медицинские услуги"),
  row("65558", "0014", "Revmoproba", "Laboratoriya", "Медицинские услуги"),
  row("65562", "0014", "Immunoferment tahlillar(IFA)", "Laboratoriya", "Медицинские услуги"),
  row("65563", "0015", "IMMUNOGLOBULINLAR", "Laboratoriya", "Медицинские услуги"),
  row("65205", "0016", "Eritrositlar cho'kish tezligi (SOE,ECHT)", "Laboratoriya", "Медицинские услуги"),
  row("65182", "0017", "Infeksiya va parazitlar", "Laboratoriya", "Медицинские услуги"),
  row("65564", "0017", "HOMA va CARO indeksi", "Laboratoriya", "Медицинские услуги"),
  row("65565", "0018", "IFA GEPATITLAR", "Laboratoriya", "Медицинские услуги"),
  row("65181", "0019", "Ekspress tahlillar", "Laboratoriya", "Медицинские услуги"),
  row("65058", "002", "Nevropotolog ko'rigi", "Shifokor ko'rigi", "Консультация"),
  row("65567", "0020", "ERKIN GEMOGLABIN", "Laboratoriya", "Медицинские услуги"),
  row("65586", "0021", "TORCH INFEKSIYALARI IgM", "Laboratoriya", "Медицинские услуги"),
  row("65184", "0021", "Torch iffeksiyalari IgG", "Laboratoriya", "Медицинские услуги"),
  row("65192", "0022", "Autoimmun tekshiruvlar", "Laboratoriya", "Медицинские услуги"),
  row("65569", "0024", "Immunofluoressent tahlillar", "Laboratoriya", "Медицинские услуги"),
  row("65570", "0025", "ONKOMARKERLAR IXLA (CLIA)", "Laboratoriya", "Медицинские услуги"),
  row("65571", "0026", "Pap Test", "Laboratoriya", "Медицинские услуги"),
  row("65572", "0027", "Prostata suyuqligi mikroskopiyasi", "Laboratoriya", "Медицинские услуги"),
  row("65553", "0028", "Siydik bioximiyasi", "Laboratoriya", "Медицинские услуги"),
  row("65554", "0029", "Siydik orqali sutkalik oqsil yo'qtish", "Laboratoriya", "Медицинские услуги"),
  row("65059", "003", "Nefrolog ko'rigi", "Shifokor ko'rigi", "Консультация"),
  row("65555", "0030", "Siydik cho'kmasi mikroskopiyasi", "Laboratoriya", "Медицинские услуги"),
  row("65587", "0031", "MAR TEST", "Laboratoriya", "Медицинские услуги"),
  row("65573", "0032", "DNK fragmentatsiyasini aniqlash testi", "Laboratoriya", "Медицинские услуги"),
  row("65574", "0033", "GEPATIT VIRUSINI PSR (PZR) usulida tekshirish", "Laboratoriya", "Медицинские услуги"),
  row("65575", "0034", "PSR (PZR) taxlillar (Qon plazmasi)", "Laboratoriya", "Медицинские услуги"),
  row("65576", "0035", "PSR (PZR) taxlillar (mazok)", "Laboratoriya", "Медицинские услуги"),
  row("65578", "0035", "PSR Virus papilloma cheloveka (VPCH) Qon zardobi", "Laboratoriya", "Медицинские услуги"),
  row("65579", "0037", "SPERMATOZOIDLARNING HAYOTIYLIGINI ANIQLASH TESTLARI", "Laboratoriya", "Медицинские услуги"),
  row("65580", "0037", "SPERMOGRAMMA VA SPERMA BIOXIMIYASI", "Laboratoriya", "Медицинские услуги"),
  row("65577", "0037", "PSR Virus papilloma cheloveka (VPCH) mazok", "Laboratoriya", "Медицинские услуги"),
  row("65581", "0038", "UROGENITAL MAZOK (Erkak)", "Laboratoriya", "Медицинские услуги"),
  row("65060", "004", "Kardiolog ko'rigi", "Shifokor ko'rigi", "Консультация"),
];
