import type { DoctorRow } from './types';

function d(
  id: string,
  code: string,
  fullName: string,
  specialty: string,
  degree: string,
  department: string,
  position: string,
  status: string,
  username: string,
  login: string,
): DoctorRow {
  return {
    id,
    code,
    fullName,
    roomNumber: '',
    specialty,
    degree,
    department,
    position,
    contact: '',
    status,
    username,
    login,
  };
}

export const INITIAL_DOCTORS: DoctorRow[] = [
  d(
    '21715',
    '001',
    'Umurov Bobir Umarovich',
    'Эндокринолог',
    '',
    "Ambulator qabul bo'limi, Statsionar bo'limi",
    'Директор',
    'Актив',
    'Umurov Bobir Umarovich',
    'gp.umurov',
  ),
  d(
    '21716',
    '002',
    'Qoryogdiyev Marufjon Komiljonovich',
    'Невропатолог',
    '',
    "Ambulator qabul bo'limi, Statsionar bo'limi",
    '',
    'Актив',
    'Qoryogdiyev Marufjon Komiljonovich',
    'gp.maruf',
  ),
  d(
    '21717',
    '003',
    'Abdulloyev Muhriddin Ziyodilloyevich',
    'Гепатолог',
    '',
    "Ambulator qabul bo'limi, Statsionar bo'limi",
    '',
    'Актив',
    '',
    '',
  ),
  d(
    '21724',
    '004',
    "Ro'ziyev Farrux Muhitdinovich",
    'УЗИ врач',
    'Высшей категории',
    "Ambulator qabul bo'limi, Statsionar bo'limi",
    '',
    'Актив',
    "Ro'ziyev Farrux Muhitdinovich",
    'gp.farrux',
  ),
  d(
    '21751',
    '005',
    'Ramazonova Navbahor Xxx',
    'Лаборант',
    'Без категории',
    "Statsionar bo'limi, Ambulator qabul bo'limi",
    '',
    'Актив',
    "Ramazonova Navbahor Jo'raqulovna",
    'gp.ramazonova',
  ),
  d(
    '21769',
    '006',
    "Ramazonova Navbahor Jo'raqul qizi",
    'Лаборант',
    '',
    "Statsionar bo'limi, Ambulator qabul bo'limi",
    '',
    'Актив',
    "Ramazonova Navbahor Jo'raqulovna",
    'gp.ramazonova',
  ),
  d(
    '21770',
    '007',
    'Rahmatov Siroj Sodiqovich',
    'Кардиолог',
    'Без категории',
    "Statsionar bo'limi, Ambulator qabul bo'limi",
    '',
    'Актив',
    'Rahmatov Siroj Sodiqovich',
    'gp.siroj',
  ),
];
